## Reference: https://github.com/amannn/action-semantic-pull-request
---
name: "Lint PR Title"

on:
  pull_request_target:
    types: [opened, edited, edited, synchronize]

permissions:
  contents: read

jobs:
  main:
    permissions:
      pull-requests: read
      statuses: write
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure which types are allowed (newline-delimited).
          # From: https://github.com/commitizen/conventional-commit-types/blob/master/index.json
          # listing all below
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
